# Generated by Django 2.2 on 2021-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(to='foody_app.User'),
        ),
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
